-- ALL REMAINING ADDICTION TRACKS - Complete Batch Deployment
-- Run this SQL to add all remaining substance and behavioral addiction tracks

-- STIMULANTS TRACK (Prescription stimulants like Adderall, Ritalin)
INSERT INTO track_modules (track_id, module_number, title, description, content, sort_order) VALUES
('stimulants', 1, 'Understanding Prescription Stimulant Dependence', 'Learn how prescription stimulants like Adderall and Ritalin can lead to dependence even when used as prescribed. Understand the unique challenges of stimulant withdrawal.', '{"lessons": [{"type": "reading", "title": "Prescription Stimulants: Medical Use vs. Dependence", "summary": "How ADHD medications can lead to physical and psychological dependence, tolerance, and withdrawal symptoms.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6165228/", "button_text": "Medical Research"}, {"type": "video", "title": "Dopamine and Stimulant Medications", "summary": "How prescription stimulants affect dopamine systems and create patterns of dependence similar to other stimulants.", "video_id": "V1bFr2SWP1I", "button_text": "Brain Effects"}, {"type": "tool", "title": "Stimulant Use Assessment", "summary": "Evaluate your stimulant use patterns, dependence indicators, and withdrawal risk factors.", "pdf_url": "/worksheets/stimulant-assessment.pdf", "button_text": "Take Assessment"}], "tools": [{"type": "wiki", "title": "ADHD vs. Stimulant Addiction", "summary": "Understanding the difference between therapeutic ADHD treatment and stimulant abuse or dependence.", "wiki_url": "/wiki/adhd-vs-stimulant-addiction", "button_text": "ADHD Considerations"}]}', 1),
('stimulants', 2, 'Managing Stimulant Withdrawal and Tapering', 'Learn to manage the depression, fatigue, and cognitive symptoms that accompany stimulant withdrawal. Understand safe tapering approaches.', '{"lessons": [{"type": "reading", "title": "Stimulant Withdrawal Syndrome", "summary": "Understanding the psychological and physical symptoms of stimulant withdrawal including depression, fatigue, and cognitive fog.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6165228/", "button_text": "Withdrawal Science"}, {"type": "video", "title": "Tapering Prescription Stimulants Safely", "summary": "Working with healthcare providers to create safe tapering schedules and manage withdrawal symptoms.", "video_id": "3X77B4b8Lh0", "button_text": "Safe Tapering"}], "tools": [{"type": "wiki", "title": "Stimulant Withdrawal Timeline", "summary": "What to expect during different phases of stimulant withdrawal and recovery.", "wiki_url": "/wiki/stimulant-withdrawal-timeline", "button_text": "Timeline Guide"}]}', 2),
('stimulants', 3, 'ADHD Management Without Stimulants', 'Learn alternative approaches to managing ADHD symptoms without stimulant medications.', '{"lessons": [{"type": "reading", "title": "Non-Stimulant ADHD Treatments", "summary": "Alternative medications and behavioral interventions for ADHD management.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6165228/", "button_text": "ADHD Alternatives"}]}', 3),
('stimulants', 4, 'Cognitive Function Recovery', 'Address the cognitive impacts of stimulant use and learn strategies for mental clarity and focus recovery.', '{"lessons": [{"type": "reading", "title": "Cognitive Recovery After Stimulants", "summary": "How the brain recovers cognitive function after stopping stimulant medications.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6165228/", "button_text": "Cognitive Recovery"}]}', 4),
('stimulants', 5, 'Academic and Work Performance', 'Develop strategies for maintaining productivity and performance without stimulant enhancement.', '{"lessons": [{"type": "reading", "title": "Productivity Without Stimulants", "summary": "Natural approaches to focus, productivity, and academic success.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6165228/", "button_text": "Natural Productivity"}]}', 5),
('stimulants', 6, 'Energy and Motivation Recovery', 'Rebuild natural energy levels and motivation systems after stimulant dependence.', '{"lessons": [{"type": "reading", "title": "Natural Energy and Motivation", "summary": "Restoring natural energy and drive without pharmaceutical enhancement.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6165228/", "button_text": "Energy Recovery"}]}', 6),
('stimulants', 7, 'Medical Provider Communication', 'Learn to work with healthcare providers for appropriate ADHD treatment and stimulant tapering.', '{"lessons": [{"type": "reading", "title": "Communicating with Doctors About Stimulant Concerns", "summary": "How to discuss stimulant dependence and treatment alternatives with medical providers.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6165228/", "button_text": "Doctor Communication"}]}', 7),
('stimulants', 8, 'Long-Term ADHD and Life Management', 'Create sustainable approaches to ADHD management and life success without stimulant dependence.', '{"lessons": [{"type": "reading", "title": "Lifelong ADHD Management", "summary": "Sustainable strategies for managing ADHD and achieving goals without stimulant dependence.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6165228/", "button_text": "Sustainable Management"}]}', 8),

-- DEPRESSANTS TRACK (Barbiturates, sedatives, other downers)
('depressants', 1, 'Understanding CNS Depressant Dependence', 'Learn how barbiturates, sedatives, and prescription downers create physical dependence and require medical supervision for safe withdrawal.', '{"lessons": [{"type": "reading", "title": "CNS Depressants: Types and Risks", "summary": "Understanding barbiturates, sedatives, and other central nervous system depressants and their dependence potential.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4365464/", "button_text": "Depressant Types"}, {"type": "video", "title": "GABA System and Depressant Withdrawal", "summary": "How CNS depressants affect the GABA system and why withdrawal can be life-threatening.", "video_id": "V1bFr2SWP1I", "button_text": "Withdrawal Science"}], "tools": [{"type": "wiki", "title": "Depressants vs. Benzodiazepines", "summary": "Understanding the similarities and differences between various CNS depressants.", "wiki_url": "/wiki/depressants-vs-benzos", "button_text": "Comparison Guide"}]}', 1),
('depressants', 2, 'Medical Withdrawal and Safety', 'Understand why depressant withdrawal requires medical supervision and proper tapering protocols.', '{"lessons": [{"type": "reading", "title": "Safe Depressant Withdrawal", "summary": "Medical protocols for safe withdrawal from CNS depressants.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4365464/", "button_text": "Medical Withdrawal"}]}', 2),
('depressants', 3, 'Sleep and Anxiety Without Depressants', 'Learn alternative approaches to managing sleep disorders and anxiety without CNS depressants.', '{"lessons": [{"type": "reading", "title": "Natural Sleep and Anxiety Management", "summary": "Evidence-based alternatives to prescription depressants for sleep and anxiety.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4365464/", "button_text": "Natural Alternatives"}]}', 3),
('depressants', 4, 'Cognitive Recovery and Function', 'Address the cognitive fog and memory issues associated with depressant use and withdrawal.', '{"lessons": [{"type": "reading", "title": "Cognitive Recovery from Depressants", "summary": "How cognitive function improves after stopping CNS depressants.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4365464/", "button_text": "Brain Recovery"}]}', 4),
('depressants', 5, 'Medical Provider Relationships', 'Learn to work with healthcare providers for appropriate treatment and tapering support.', '{"lessons": [{"type": "reading", "title": "Healthcare Provider Communication", "summary": "How to discuss depressant dependence and treatment options with medical professionals.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4365464/", "button_text": "Provider Communication"}]}', 5),
('depressants', 6, 'Underlying Condition Management', 'Address the underlying conditions that led to depressant prescription without creating dependence.', '{"lessons": [{"type": "reading", "title": "Treating Root Causes", "summary": "Managing sleep disorders, anxiety, and other conditions without dependence-forming medications.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4365464/", "button_text": "Root Cause Treatment"}]}', 6),
('depressants', 7, 'Emergency Preparedness', 'Understand emergency protocols and safety planning for depressant withdrawal complications.', '{"lessons": [{"type": "reading", "title": "Withdrawal Emergency Planning", "summary": "Safety planning and emergency protocols for serious withdrawal complications.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4365464/", "button_text": "Emergency Planning"}]}', 7),
('depressants', 8, 'Long-Term Recovery and Prevention', 'Create sustainable recovery plans and prevent future dependence on CNS depressants.', '{"lessons": [{"type": "reading", "title": "Sustainable Recovery from Depressants", "summary": "Long-term strategies for maintaining recovery and preventing relapse.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4365464/", "button_text": "Long-Term Recovery"}]}', 8),

-- NICOTINE TRACK (Smoking, vaping, tobacco products)
('nicotine', 1, 'Understanding Nicotine Addiction: Smoking, Vaping, and Tobacco', 'Learn how nicotine creates powerful addiction through cigarettes, vapes, and other tobacco products. Understand why quitting is so challenging.', '{"lessons": [{"type": "reading", "title": "Nicotine Addiction: The Most Common Addiction", "summary": "How nicotine creates powerful addiction and why it''s one of the hardest substances to quit.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4669730/", "button_text": "Nicotine Science"}, {"type": "video", "title": "Smoking vs. Vaping: Different Delivery, Same Addiction", "summary": "How different nicotine delivery methods (cigarettes, vapes, patches, pouches) affect addiction potential.", "video_id": "V1bFr2SWP1I", "button_text": "Delivery Methods"}, {"type": "tool", "title": "Nicotine Dependence Assessment", "summary": "Assess your level of nicotine dependence using validated screening tools.", "pdf_url": "/worksheets/nicotine-dependence-assessment.pdf", "button_text": "Take Assessment"}], "tools": [{"type": "wiki", "title": "Vaping vs. Smoking: Health and Addiction Differences", "summary": "Comparing the health risks and addiction potential of different nicotine products.", "wiki_url": "/wiki/vaping-vs-smoking", "button_text": "Product Comparison"}]}', 1),
('nicotine', 2, 'Nicotine Withdrawal and Quitting Strategies', 'Learn about different quitting methods and how to manage nicotine withdrawal symptoms effectively.', '{"lessons": [{"type": "reading", "title": "Nicotine Withdrawal: Timeline and Symptoms", "summary": "Understanding the physical and psychological symptoms of nicotine withdrawal and how long they last.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4669730/", "button_text": "Withdrawal Timeline"}, {"type": "video", "title": "Cold Turkey vs. Gradual Reduction vs. NRT", "summary": "Comparing different quitting approaches: cold turkey, gradual reduction, and nicotine replacement therapy.", "video_id": "3X77B4b8Lh0", "button_text": "Quitting Methods"}, {"type": "reading", "title": "Nicotine Replacement Therapy Options", "summary": "Understanding patches, gum, lozenges, and other NRT options for managing withdrawal.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4669730/", "button_text": "NRT Options"}], "tools": [{"type": "wiki", "title": "Managing Nicotine Cravings", "summary": "Evidence-based strategies for managing intense nicotine cravings and urges.", "wiki_url": "/wiki/nicotine-craving-management", "button_text": "Craving Management"}]}', 2),
('nicotine', 3, 'Triggers and Habit Breaking', 'Identify and break the behavioral patterns and triggers associated with nicotine use.', '{"lessons": [{"type": "reading", "title": "Breaking Nicotine Habits and Triggers", "summary": "Identifying and changing the behavioral patterns that trigger nicotine use.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4669730/", "button_text": "Habit Breaking"}]}', 3),
('nicotine', 4, 'Health Recovery and Benefits', 'Understand the timeline of health improvements after quitting nicotine and tobacco products.', '{"lessons": [{"type": "reading", "title": "Health Benefits Timeline After Quitting", "summary": "How your body heals and improves after stopping nicotine and tobacco use.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4669730/", "button_text": "Health Recovery"}]}', 4),
('nicotine', 5, 'Weight Management and Metabolism', 'Address weight gain concerns and metabolic changes that can occur when quitting nicotine.', '{"lessons": [{"type": "reading", "title": "Weight Management After Quitting Nicotine", "summary": "Understanding and managing weight changes during nicotine cessation.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4669730/", "button_text": "Weight Management"}]}', 5),
('nicotine', 6, 'Social Situations and Peer Pressure', 'Navigate social situations and peer pressure related to smoking and vaping.', '{"lessons": [{"type": "reading", "title": "Social Aspects of Quitting Nicotine", "summary": "Handling social situations and peer pressure when quitting nicotine products.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4669730/", "button_text": "Social Navigation"}]}', 6),
('nicotine', 7, 'Stress Management Without Nicotine', 'Learn healthy stress management techniques to replace nicotine as a coping mechanism.', '{"lessons": [{"type": "reading", "title": "Stress Management in Nicotine Recovery", "summary": "Healthy alternatives to nicotine for managing stress and difficult emotions.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4669730/", "button_text": "Stress Alternatives"}]}', 7),
('nicotine', 8, 'Long-Term Recovery and Relapse Prevention', 'Create sustainable strategies for maintaining nicotine-free life and preventing relapse.', '{"lessons": [{"type": "reading", "title": "Maintaining Long-Term Nicotine Freedom", "summary": "Strategies for staying quit long-term and preventing nicotine relapse.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4669730/", "button_text": "Long-Term Success"}]}', 8),

-- PORNOGRAPHY TRACK (Compulsive sexual behavior)
('pornography', 1, 'Understanding Pornography Addiction and Compulsive Sexual Behavior', 'Learn how pornography consumption can become compulsive and addictive, affecting brain chemistry, relationships, and sexual health.', '{"lessons": [{"type": "reading", "title": "Compulsive Sexual Behavior Disorder: WHO Recognition", "summary": "Understanding how the WHO recognizes compulsive sexual behavior disorder and its relationship to pornography use.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6352245/", "button_text": "Medical Recognition"}, {"type": "video", "title": "Pornography and Brain Chemistry", "summary": "How pornography affects dopamine pathways and creates patterns similar to substance addictions.", "video_id": "V1bFr2SWP1I", "button_text": "Brain Effects"}, {"type": "tool", "title": "Compulsive Sexual Behavior Assessment", "summary": "Assess your pornography use patterns and their impact on your life and relationships.", "pdf_url": "/worksheets/pornography-addiction-assessment.pdf", "button_text": "Take Assessment"}], "tools": [{"type": "wiki", "title": "Pornography Addiction vs. Healthy Sexuality", "summary": "Understanding the difference between healthy sexual expression and compulsive pornography use.", "wiki_url": "/wiki/healthy-sexuality-vs-addiction", "button_text": "Healthy Sexuality"}]}', 1),
('pornography', 2, 'Breaking the Pornography Cycle and Managing Withdrawal', 'Learn to break compulsive pornography use patterns and manage the psychological withdrawal symptoms.', '{"lessons": [{"type": "reading", "title": "Pornography Withdrawal and Recovery Timeline", "summary": "Understanding the psychological symptoms and timeline of recovery from pornography addiction.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6352245/", "button_text": "Recovery Timeline"}, {"type": "video", "title": "Breaking Compulsive Behavioral Patterns", "summary": "Strategies for interrupting automatic pornography use patterns and building new neural pathways.", "video_id": "3X77B4b8Lh0", "button_text": "Pattern Breaking"}], "tools": [{"type": "wiki", "title": "Pornography Blockers and Environmental Controls", "summary": "Technical solutions and environmental changes to reduce access and triggers.", "wiki_url": "/wiki/pornography-blocking-tools", "button_text": "Blocking Tools"}]}', 2),
('pornography', 3, 'Sexual Health and Function Recovery', 'Address the impacts of pornography use on sexual health and intimate relationships.', '{"lessons": [{"type": "reading", "title": "Sexual Function Recovery", "summary": "How sexual health and function improve after stopping pornography use.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6352245/", "button_text": "Sexual Recovery"}]}', 3),
('pornography', 4, 'Relationship Healing and Intimacy', 'Rebuild trust and intimacy in relationships affected by pornography addiction.', '{"lessons": [{"type": "reading", "title": "Rebuilding Relationship Trust", "summary": "How to heal relationships damaged by compulsive pornography use.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6352245/", "button_text": "Relationship Healing"}]}', 4),
('pornography', 5, 'Shame and Self-Worth Recovery', 'Address shame, guilt, and self-worth issues commonly associated with pornography addiction.', '{"lessons": [{"type": "reading", "title": "Overcoming Shame in Recovery", "summary": "Addressing shame and rebuilding healthy self-worth during recovery.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6352245/", "button_text": "Shame Recovery"}]}', 5),
('pornography', 6, 'Healthy Sexuality Development', 'Learn to develop healthy sexual attitudes and behaviors independent of pornography.', '{"lessons": [{"type": "reading", "title": "Developing Healthy Sexual Expression", "summary": "Building healthy sexual attitudes and behaviors after pornography addiction.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6352245/", "button_text": "Healthy Expression"}]}', 6),
('pornography', 7, 'Trigger Management and Relapse Prevention', 'Identify and manage triggers that lead to compulsive pornography use.', '{"lessons": [{"type": "reading", "title": "Managing Pornography Triggers", "summary": "Identifying and managing environmental, emotional, and psychological triggers.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6352245/", "button_text": "Trigger Management"}]}', 7),
('pornography', 8, 'Long-Term Recovery and Healthy Relationships', 'Build sustainable recovery and healthy intimate relationships free from compulsive sexual behavior.', '{"lessons": [{"type": "reading", "title": "Sustainable Recovery from Pornography Addiction", "summary": "Long-term strategies for maintaining recovery and building healthy relationships.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6352245/", "button_text": "Long-Term Success"}]}', 8),

-- GAMBLING TRACK 
('gambling', 1, 'Understanding Gambling Disorder and the Psychology of Risk', 'Learn how gambling becomes addictive through psychological manipulation, variable ratio reinforcement, and the illusion of control.', '{"lessons": [{"type": "reading", "title": "Gambling Disorder: DSM-5 Criteria and Recognition", "summary": "Understanding gambling disorder as a recognized mental health condition with specific diagnostic criteria.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4330000/", "button_text": "Medical Recognition"}, {"type": "video", "title": "The Psychology of Gambling: How Casinos Hook Players", "summary": "How gambling establishments use psychological manipulation to create and maintain addiction.", "video_id": "V1bFr2SWP1I", "button_text": "Gambling Psychology"}, {"type": "tool", "title": "Gambling Disorder Assessment", "summary": "Assess your gambling behavior and its impact on your life using validated screening tools.", "pdf_url": "/worksheets/gambling-disorder-assessment.pdf", "button_text": "Take Assessment"}], "tools": [{"type": "wiki", "title": "Types of Gambling and Addiction Risk", "summary": "How different types of gambling (slots, sports betting, poker, lottery) create different addiction patterns.", "wiki_url": "/wiki/gambling-types-addiction-risk", "button_text": "Gambling Types"}]}', 1),
('gambling', 2, 'Financial Recovery and Damage Assessment', 'Assess the financial damage from gambling and create realistic plans for financial recovery and debt management.', '{"lessons": [{"type": "reading", "title": "Assessing Gambling Financial Damage", "summary": "How to thoroughly assess the financial impact of gambling addiction and create recovery plans.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4330000/", "button_text": "Financial Assessment"}, {"type": "video", "title": "Debt Management and Financial Recovery", "summary": "Strategies for managing gambling debt and rebuilding financial stability.", "video_id": "3X77B4b8Lh0", "button_text": "Debt Recovery"}, {"type": "tool", "title": "Financial Recovery Planner", "summary": "Create a comprehensive plan for financial recovery and debt management after gambling addiction.", "pdf_url": "/worksheets/gambling-financial-recovery.pdf", "button_text": "Financial Planning"}], "tools": [{"type": "wiki", "title": "Gambling Exclusion Programs", "summary": "How to use self-exclusion programs and gambling blocks to prevent access to gambling venues and websites.", "wiki_url": "/wiki/gambling-exclusion-programs", "button_text": "Exclusion Programs"}]}', 2),
('gambling', 3, 'Cognitive Distortions and Thinking Errors', 'Address the thinking errors and cognitive distortions that fuel gambling addiction.', '{"lessons": [{"type": "reading", "title": "Gambling Cognitive Distortions", "summary": "Identifying and correcting the thinking errors that maintain gambling addiction.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4330000/", "button_text": "Thinking Errors"}]}', 3),
('gambling', 4, 'Emotional Regulation and Triggers', 'Learn to manage the emotions and triggers that lead to gambling episodes.', '{"lessons": [{"type": "reading", "title": "Emotional Triggers in Gambling", "summary": "Understanding and managing the emotional states that trigger gambling urges.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4330000/", "button_text": "Emotional Management"}]}', 4),
('gambling', 5, 'Relationship Repair and Trust Rebuilding', 'Address the relationship damage caused by gambling addiction and rebuild trust with family and friends.', '{"lessons": [{"type": "reading", "title": "Rebuilding Trust After Gambling", "summary": "How to repair relationships damaged by gambling addiction and financial betrayal.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4330000/", "button_text": "Trust Rebuilding"}]}', 5),
('gambling', 6, 'Career and Work Recovery', 'Address career damage from gambling and rebuild professional reputation and financial stability.', '{"lessons": [{"type": "reading", "title": "Career Recovery After Gambling Addiction", "summary": "Rebuilding professional life and financial stability after gambling-related career damage.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4330000/", "button_text": "Career Recovery"}]}', 6),
('gambling', 7, 'Legal Issues and Financial Crimes', 'Address legal complications that may arise from gambling-related financial problems.', '{"lessons": [{"type": "reading", "title": "Legal Issues in Gambling Recovery", "summary": "Dealing with legal consequences and financial crimes related to gambling addiction.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4330000/", "button_text": "Legal Recovery"}]}', 7),
('gambling', 8, 'Long-Term Financial Health and Recovery Maintenance', 'Build sustainable financial practices and long-term recovery strategies.', '{"lessons": [{"type": "reading", "title": "Long-Term Gambling Recovery", "summary": "Sustainable strategies for maintaining gambling recovery and building financial health.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4330000/", "button_text": "Long-Term Success"}]}', 8),

-- SHOPPING TRACK (Compulsive buying disorder)
('shopping', 1, 'Understanding Compulsive Buying and Shopping Addiction', 'Learn how shopping becomes addictive through emotional regulation, social status seeking, and instant gratification patterns.', '{"lessons": [{"type": "reading", "title": "Compulsive Buying Disorder: Psychology and Patterns", "summary": "Understanding the psychological mechanisms behind compulsive shopping and spending addiction.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6174874/", "button_text": "Shopping Psychology"}, {"type": "video", "title": "Retail Therapy vs. Shopping Addiction", "summary": "Understanding the difference between occasional retail therapy and compulsive buying disorder.", "video_id": "V1bFr2SWP1I", "button_text": "Addiction vs. Therapy"}, {"type": "tool", "title": "Compulsive Buying Assessment", "summary": "Assess your shopping behaviors and their impact on your finances and well-being.", "pdf_url": "/worksheets/shopping-addiction-assessment.pdf", "button_text": "Take Assessment"}], "tools": [{"type": "wiki", "title": "Online Shopping vs. In-Store Addiction", "summary": "How different shopping environments (online, in-store, social media) trigger compulsive buying.", "wiki_url": "/wiki/shopping-environments-addiction", "button_text": "Shopping Environments"}]}', 1),
('shopping', 2, 'Financial Recovery and Spending Control', 'Assess financial damage from compulsive shopping and implement practical spending controls and recovery strategies.', '{"lessons": [{"type": "reading", "title": "Financial Impact Assessment and Recovery", "summary": "How to assess the financial damage from shopping addiction and create realistic recovery plans.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6174874/", "button_text": "Financial Recovery"}, {"type": "video", "title": "Budgeting and Spending Controls", "summary": "Practical strategies for controlling spending and creating sustainable budgets.", "video_id": "3X77B4b8Lh0", "button_text": "Spending Control"}, {"type": "tool", "title": "Shopping Recovery Budget Planner", "summary": "Create budgets and spending plans designed for shopping addiction recovery.", "pdf_url": "/worksheets/shopping-budget-planner.pdf", "button_text": "Budget Planning"}], "tools": [{"type": "wiki", "title": "Shopping Addiction Barriers and Controls", "summary": "Practical barriers to prevent impulsive shopping including apps, account controls, and environmental changes.", "wiki_url": "/wiki/shopping-addiction-barriers", "button_text": "Shopping Barriers"}]}', 2),
('shopping', 3, 'Emotional Triggers and Regulation', 'Identify and manage the emotions that drive compulsive shopping behavior.', '{"lessons": [{"type": "reading", "title": "Emotional Shopping Triggers", "summary": "Understanding and managing the emotional states that trigger compulsive buying.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6174874/", "button_text": "Emotional Management"}]}', 3),
('shopping', 4, 'Consumer Culture and Social Pressure', 'Address the social and cultural pressures that fuel shopping addiction in consumer society.', '{"lessons": [{"type": "reading", "title": "Consumer Culture and Identity", "summary": "How consumer culture and social media fuel shopping addiction and material identity.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6174874/", "button_text": "Consumer Psychology"}]}', 4),
('shopping', 5, 'Decluttering and Possession Management', 'Learn to manage accumulated possessions and develop healthier relationships with material goods.', '{"lessons": [{"type": "reading", "title": "Decluttering and Minimalism", "summary": "Strategies for managing accumulated items and developing minimalist approaches to possessions.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6174874/", "button_text": "Possession Management"}]}', 5),
('shopping', 6, 'Alternative Activities and Fulfillment', 'Find non-material sources of satisfaction and fulfillment to replace shopping highs.', '{"lessons": [{"type": "reading", "title": "Non-Material Sources of Fulfillment", "summary": "Discovering satisfaction and fulfillment through experiences, relationships, and personal growth rather than purchases.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6174874/", "button_text": "Alternative Fulfillment"}]}', 6),
('shopping', 7, 'Relationship Impact and Social Recovery', 'Address how shopping addiction affects relationships and social interactions.', '{"lessons": [{"type": "reading", "title": "Shopping Addiction and Relationships", "summary": "How compulsive buying affects relationships and strategies for social recovery.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6174874/", "button_text": "Relationship Recovery"}]}', 7),
('shopping', 8, 'Sustainable Consumption and Long-Term Recovery', 'Develop sustainable consumption habits and long-term recovery strategies.', '{"lessons": [{"type": "reading", "title": "Sustainable Shopping Recovery", "summary": "Long-term strategies for maintaining healthy consumption habits and financial wellness.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6174874/", "button_text": "Sustainable Recovery"}]}', 8),

-- FOOD TRACK (Binge eating disorder, food addiction)
('food', 1, 'Understanding Food Addiction and Binge Eating Disorder', 'Learn how certain foods create addictive patterns and how binge eating disorder differs from normal eating struggles.', '{"lessons": [{"type": "reading", "title": "Food Addiction: Science and Controversy", "summary": "Understanding the scientific evidence for food addiction and how processed foods affect brain chemistry.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6234835/", "button_text": "Food Addiction Science"}, {"type": "video", "title": "Binge Eating Disorder vs. Overeating", "summary": "Understanding the difference between binge eating disorder and normal overeating or food struggles.", "video_id": "V1bFr2SWP1I", "button_text": "BED vs. Overeating"}, {"type": "tool", "title": "Binge Eating Disorder Assessment", "summary": "Assess your eating patterns and their impact on your physical and mental health.", "pdf_url": "/worksheets/binge-eating-assessment.pdf", "button_text": "Take Assessment"}], "tools": [{"type": "wiki", "title": "Trigger Foods and Addiction Potential", "summary": "Understanding which foods are most likely to trigger addictive eating patterns.", "wiki_url": "/wiki/trigger-foods-addiction", "button_text": "Trigger Foods"}]}', 1),
('food', 2, 'Breaking Binge Cycles and Emotional Eating Patterns', 'Learn to interrupt binge eating cycles and address the emotional triggers that lead to compulsive eating.', '{"lessons": [{"type": "reading", "title": "Breaking the Binge-Restrict Cycle", "summary": "Understanding how restriction leads to binging and how to break this destructive cycle.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6234835/", "button_text": "Cycle Breaking"}, {"type": "video", "title": "Emotional Eating vs. Physical Hunger", "summary": "Learning to distinguish between emotional eating triggers and true physical hunger.", "video_id": "3X77B4b8Lh0", "button_text": "Hunger Recognition"}], "tools": [{"type": "wiki", "title": "Mindful Eating Techniques", "summary": "Evidence-based mindful eating practices for developing a healthier relationship with food.", "wiki_url": "/wiki/mindful-eating-techniques", "button_text": "Mindful Eating"}]}', 2),
('food', 3, 'Nutritional Recovery and Health', 'Address the physical health impacts of binge eating and develop sustainable nutrition practices.', '{"lessons": [{"type": "reading", "title": "Nutritional Recovery from Binge Eating", "summary": "How to restore physical health and develop sustainable nutrition habits after binge eating disorder.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6234835/", "button_text": "Nutritional Health"}]}', 3),
('food', 4, 'Body Image and Self-Acceptance', 'Address body image issues and develop self-acceptance independent of weight and appearance.', '{"lessons": [{"type": "reading", "title": "Body Image Recovery", "summary": "Developing a healthy body image and self-acceptance in eating disorder recovery.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6234835/", "button_text": "Body Image Healing"}]}', 4),
('food', 5, 'Social Eating and Relationship Recovery', 'Navigate social eating situations and repair relationships affected by eating behaviors.', '{"lessons": [{"type": "reading", "title": "Social Eating in Recovery", "summary": "How to handle social eating situations and rebuild relationships affected by eating disorders.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6234835/", "button_text": "Social Recovery"}]}', 5),
('food', 6, 'Exercise and Movement Recovery', 'Develop a healthy relationship with exercise and physical activity after eating disorder recovery.', '{"lessons": [{"type": "reading", "title": "Exercise and Eating Disorder Recovery", "summary": "Building a healthy relationship with exercise and movement in eating disorder recovery.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6234835/", "button_text": "Exercise Recovery"}]}', 6),
('food', 7, 'Shame and Mental Health Recovery', 'Address shame, guilt, and mental health issues associated with binge eating and food addiction.', '{"lessons": [{"type": "reading", "title": "Mental Health in Eating Recovery", "summary": "Addressing shame, depression, and anxiety in eating disorder and food addiction recovery.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6234835/", "button_text": "Mental Health Recovery"}]}', 7),
('food', 8, 'Long-Term Recovery and Intuitive Eating', 'Develop sustainable eating practices and long-term recovery strategies.', '{"lessons": [{"type": "reading", "title": "Sustainable Eating Recovery", "summary": "Long-term strategies for maintaining eating disorder recovery and developing intuitive eating.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6234835/", "button_text": "Sustainable Recovery"}]}', 8),

-- WORK TRACK (Workaholism, work addiction)
('work', 1, 'Understanding Workaholism and Compulsive Work Patterns', 'Learn how work becomes addictive through achievement validation, avoidance behaviors, and cultural reinforcement of overwork.', '{"lessons": [{"type": "reading", "title": "Workaholism: Addiction or Cultural Norm?", "summary": "Understanding the difference between high achievement and compulsive work addiction.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5573583/", "button_text": "Work Addiction Science"}, {"type": "video", "title": "The Psychology of Work Addiction", "summary": "How work addiction develops through perfectionism, control needs, and avoidance of other life areas.", "video_id": "V1bFr2SWP1I", "button_text": "Work Psychology"}, {"type": "tool", "title": "Workaholism Assessment Scale", "summary": "Assess your work patterns and their impact on your health, relationships, and well-being.", "pdf_url": "/worksheets/workaholism-assessment.pdf", "button_text": "Take Assessment"}], "tools": [{"type": "wiki", "title": "Work Addiction vs. High Performance", "summary": "Understanding the difference between healthy high performance and compulsive work addiction.", "wiki_url": "/wiki/work-addiction-vs-performance", "button_text": "Performance vs. Addiction"}]}', 1),
('work', 2, 'Establishing Work-Life Balance and Healthy Boundaries', 'Learn to set appropriate boundaries between work and personal life and develop sustainable work practices.', '{"lessons": [{"type": "reading", "title": "Setting Work Boundaries and Limits", "summary": "Practical strategies for setting healthy boundaries between work and personal life.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5573583/", "button_text": "Boundary Setting"}, {"type": "video", "title": "Time Management vs. Time Boundaries", "summary": "Learning to manage time effectively while maintaining healthy limits on work hours.", "video_id": "3X77B4b8Lh0", "button_text": "Time Boundaries"}], "tools": [{"type": "wiki", "title": "Technology Boundaries for Work Recovery", "summary": "Managing work technology (email, Slack, phone) to support work-life balance recovery.", "wiki_url": "/wiki/work-technology-boundaries", "button_text": "Tech Boundaries"}]}', 2),
('work', 3, 'Perfectionism and Control Recovery', 'Address perfectionist tendencies and control issues that fuel work addiction.', '{"lessons": [{"type": "reading", "title": "Perfectionism in Work Addiction", "summary": "Understanding and addressing perfectionist patterns that drive compulsive work behaviors.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5573583/", "button_text": "Perfectionism Recovery"}]}', 3),
('work', 4, 'Stress Management and Burnout Recovery', 'Learn to manage work stress and recover from burnout while maintaining career success.', '{"lessons": [{"type": "reading", "title": "Burnout Recovery and Prevention", "summary": "Strategies for recovering from work burnout and preventing future stress-related health problems.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5573583/", "button_text": "Burnout Recovery"}]}', 4),
('work', 5, 'Relationship Recovery and Social Life', 'Rebuild relationships and social connections damaged by work addiction and overcommitment.', '{"lessons": [{"type": "reading", "title": "Relationship Recovery from Workaholism", "summary": "How to repair relationships damaged by work addiction and rebuild social connections.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5573583/", "button_text": "Relationship Repair"}]}', 5),
('work', 6, 'Identity Beyond Work Achievement', 'Develop a sense of identity and self-worth independent of work accomplishments.', '{"lessons": [{"type": "reading", "title": "Identity Beyond Work Success", "summary": "Building self-worth and identity that doesn''t depend solely on work achievements and career success.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5573583/", "button_text": "Identity Recovery"}]}', 6),
('work', 7, 'Health and Self-Care Recovery', 'Address the physical and mental health impacts of work addiction and develop self-care practices.', '{"lessons": [{"type": "reading", "title": "Health Recovery from Work Addiction", "summary": "Addressing the physical and mental health consequences of chronic overwork and stress.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5573583/", "button_text": "Health Recovery"}]}', 7),
('work', 8, 'Sustainable Career Success and Life Integration', 'Create sustainable approaches to career success that integrate work with other life values.', '{"lessons": [{"type": "reading", "title": "Sustainable Work-Life Integration", "summary": "Long-term strategies for maintaining career success while living a balanced, fulfilling life.", "external_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5573583/", "button_text": "Sustainable Success"}]}', 8)

ON CONFLICT (track_id, module_number) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    content = EXCLUDED.content,
    sort_order = EXCLUDED.sort_order,
    updated_at = NOW();
