name: Supabase DB Push

on:
  push:
    branches: [ main ]
    paths:
      - 'supabase/migrations/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  push-migrations:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1

      - name: Supabase CLI Version
        run: supabase --version

      - name: Login to Supabase (non-interactive)
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: supabase login --token "$SUPABASE_ACCESS_TOKEN"

      - name: Link project
        run: supabase link --project-ref avlfffrocdabopmssohw

      - name: Push migrations to remote (non-interactive)
        env:
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          # Force Go resolver to prefer IPv4 to avoid IPv6 connectivity issues in runners
          GODEBUG: ipv6=0
          PGCONNECT_TIMEOUT: 20
        run: |
          # Use pooled connection host and correct port (6543) with project-scoped user
          DB_URL="postgres://postgres.avlfffrocdabopmssohw:${SUPABASE_DB_PASSWORD}@aws-0-us-east-2.pooler.supabase.com:6543/postgres?sslmode=require"
          supabase db push --db-url "$DB_URL" --debug


