name: Supabase DB Push

on:
  push:
    branches: [ main ]
    paths:
      - 'supabase/migrations/**'

permissions:
  contents: read

jobs:
  push-migrations:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1

      - name: Supabase CLI Version
        run: supabase --version

      - name: Login to Supabase (non-interactive)
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: supabase login --token "$SUPABASE_ACCESS_TOKEN"

      - name: Link project
        run: supabase link --project-ref avlfffrocdabopmssohw

      - name: Push migrations to remote (non-interactive)
        env:
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        run: |
          # Construct a direct Postgres connection string to avoid interactive prompts
          DB_URL="postgres://postgres:${SUPABASE_DB_PASSWORD}@db.avlfffrocdabopmssohw.supabase.co:5432/postgres?sslmode=require"
          # Push migrations using the explicit DB URL
          supabase db push --db-url "$DB_URL" --debug


